### ISSUE TITLE
Retrieve VIN

### ISSUE THREAD

**Issue by jumpjack** [db-EV/ZoePHP#10]
With this snippet of code you can retrieve VIN:

```
//Request VIN
  $postData = array(
    'apikey: '.$kamereon_api,
    'x-gigya-id_token: '.$id_token,
  );
  $ch = curl_init('https://api-wired-prod-1-euw1.wrd-aws.com/commerce/v1/accounts/'.$accountId2.'/vehicles?country='.$country);
  curl_setopt($ch, CURLOPT_RETURNTRANSFER, TRUE);
  curl_setopt($ch, CURLOPT_HTTPHEADER, $postData);
  $response = curl_exec($ch);
  if ($response === FALSE) die(curl_error($ch));
  $responseData = json_decode($response, TRUE);
  $VIN = $responseData['vehicleLinks']['vehicleDetails'][0]['vin'];
echo"<br><br>VIN response:<br><pre>" .  json_encode(json_decode($response), JSON_PRETTY_PRINT) . "</pre><br><br>";
echo "<br><br>VIN:<br>" .  $vin . "<br><br>";
```

The "trick" is to use the second account number, which you can retrieve adding this line to the account retrieval code:
  `$accountId2 = $responseData['accounts'][1]['accountId'];`

It has property "accountType" = "MYRENAULT".

**Comment by db-EV** [comment]
It's a good idea to receive the VIN directly from the account. The VIN should be saved in the session file to minimize number of API calls.
And the snippet above works only with one car registered the account, are there more than one car on the same MYR account it don't work.

**Comment by jumpjack** [comment]
And you should also take care of the type of the account: **maybe** the myrenault account is always second one, maybe not, so it would be better to check for "accountType" value.
