### ISSUE TITLE
Choose between Google Maps and OpenStreetMap

### ISSUE THREAD

**Issue by db-EV** [db-EV/ZoePHP#17]
Idea from "Syon" on GoingElectric forum how to change from Google Maps to OpenStreetMap.
I will maybe include an option for choosing either Google Maps or OpenStreetMap for the Ph2-link.

**Comment by sorryusernameisalreadytaken** [comment]
I like it! +1

**Comment by db-EV** [comment]
https://github.com/db-EV/ZoePHP/commit/209b49194e6e7b1c4ec09a18ff1c14583a8978af

**Comment by db-EV** [comment]
See commits https://github.com/db-EV/ZoePHP/commit/209b49194e6e7b1c4ec09a18ff1c14583a8978af and https://github.com/db-EV/ZoePHP/commit/430823b8d69b5709811844ef646f1be5c28a59ca.

**Comment by db-EV** [comment]
Added in https://github.com/db-EV/ZoePHP/releases/tag/20220316
