### ISSUE TITLE
Renault API broken?

### ISSUE THREAD

**Issue by jumpjack** [db-EV/ZoePHP#19]
I think something changed on Renault server, breaking all 3rd party apps...

**Comment by db-EV** [comment]
Kamereon API key changed?

**Comment by db-EV** [comment]
No, the Kamereon API key isn't included in the JSON-files. It's hardcoded in the app if I remember correct.

**Comment by db-EV** [comment]
Fixed in https://github.com/db-EV/ZoePHP/releases/tag/20220316

**Comment by jumpjack** [comment]
New Kamereon API key is:
`VAX7XYKGfa92yMvXculCkEFyfZbuM7Ss`

**Comment by OE2WNL** [comment]
Thanks for the quick fix

**Comment by something-wrong** [comment]
Is there no API Key for switzerland?
