### ISSUE TITLE
Renault server connection fails

### ISSUE THREAD

**Issue by Andycool29** [db-EV/ZoePHP#21]
Since 16th march connection to Renault Server ist not working anymore. 
debug.phb sends "Access denied" "Unauthorized" message.

My Renault App is still working. Do I need a new API code? Any other idea?

**Comment by Andycool29** [comment]
I´m using following API:
$DE = '3_7PLksOyBRkHv126x5WhHb-5pqC1qFR8pQjxSeLB6nhAnPERTUlwnYoznHSxwX668';

**Comment by db-EV** [comment]
Kamereon key was changed - see https://github.com/db-EV/ZoePHP/issues/19.
Fixed on same day with release https://github.com/db-EV/ZoePHP/releases/tag/20220316.
