### ISSUE TITLE
History : additional computed data

### ISSUE THREAD

**Issue by Malimalo** [db-EV/ZoePHP#24]
I've added on my side the average charging power in the history.

Start:  27.01.2023 18:50
Charging:  25.4 kWh in 25 minutes
Avg. Charging power:  60.96 kW
Status:  ok at 27.01.2023 19:16

If anyone else is interesting, I can contribute...

**Comment by db-EV** [comment]
Thanks @Malimalo for your contribution. I will check it next weekend :-)

**Comment by db-EV** [comment]
Added in release [20230221](https://github.com/db-EV/ZoePHP/releases/tag/20230221).
