### ISSUE TITLE
Use with ABRP

### ISSUE THREAD

**Issue by Malimalo** [db-EV/ZoePHP#27]
Hi, I'm trying to use the Cron to feed Abrp. I set the Cron refresh rate to 15 min. It's not short enough to have live data in Abrp. 
I'm wondering if :
- I should set 1 minute to the Cron refresh rate, but I'm worried about impact on battery when I'm not using the car...
- I should try to identify when the car is moving to have different refreshing rates when car is running, or when car is parked (similar to when the car is charging...)

What do you think ?

**Comment by db-EV** [comment]
The cron refresh rate has no impact on the cars battery life. The car is sending data to the Renault servers on its own cycle and isn't impact by how often you read data from the Renault servers.

But it can happen that you run in an API rate limit when you have a short cron refresh rate, especially when you're using the My Renault App or other integrations at the same time.

How often your car is sending data to the Renault servers is depending on which car model you are using, Zoe Ph1, Ph2 or an other electric Renault.
