### ISSUE TITLE
Access denied

### ISSUE THREAD

**Issue by db-EV** [db-EV/ZoePHP#28]
Since today I'm can't receive any data anymore.
Error from debug.php on all requests:
{"error":"access_denied","error_description":"Unauthorized"}

**Comment by bobybc** [comment]
Kamereon API changed . The new value is YjkKtHmGfaceeuExUDKGxrLZGGvtVS0J

**Comment by schoenf** [comment]
> Kamereon API changed . The new value is YjkKtHmGfaceeuExUDKGxrLZGGvtVS0J

Works for me, thank you!

**Comment by Nunmalfix** [comment]
Same problem in Germany - wrong API Key

**Comment by db-EV** [comment]
Fixed in release 20230418. Thanks to @TheReiner (I think he was [first](url=https://github.com/home-assistant/core/issues/91593#issuecomment-1513059497))!
