### ISSUE TITLE
PHP Warning from cron job

### ISSUE THREAD

**Issue by abaum26** [db-EV/ZoePHP#29]
For a few days now, I have been receiving the following error message from the cron job I have set up:

`PHP Warning:  Undefined array key "current" in /var/www/vhosts/httpdocs/megane/index.php on line 308 PHP Warning:  Trying to access array offset on value of type null in /var/www/vhosts/httpdocs/megane/index.php on line 308 PHP Warning:  Undefined array key "current" in /var/www/vhosts/httpdocs/megane/index.php on line 309 PHP Warning:  Trying to access array offset on value of type null in /var/www/vhosts/httpdocs/megane/index.php on line 309 PHP Warning:  Trying to access array offset on value of type null in /var/www/vhosts/httpdocs/megane/index.php on line 309 PHP Warning:  Trying to access array offset on value of type null in /var/www/vhosts/httpdocs/megane/index.php on line 309`

There is another process running on the server for a Zoe that is not reporting any errors. Installed is the latest version with the customized api-keys.php.

Megane
PHP-Version: 8.2.6
cron: */1 * * * * 

Zoe
PHP-Version: 8.2.6
Folder: /var/www/vhosts/httpdocs/zoe/index.php
cron: */5 * * * * 

I suspect that the error lies with me. Maybe someone knows the problem. At least the correct values seem to be transmitted.

Thanks for your help!

**Comment by db-EV** [comment]
This indicates a problem with getting data from the openweathermap API.
Did you changed the config.php? There is the API key for openweathermap defined.

**Comment by db-EV** [comment]
Closed because no answer to my question.
