### ISSUE TITLE
Undefined array key "plugStatus" index.php on line 217

### ISSUE THREAD

**Issue by DemianosHB** [db-EV/ZoePHP#30]
Hi there,

I'm using your script for an MeganE, so my config is $zoeph = 2;

It seems like the Plug Status can't be obtained via the cameron API?
My Apache log says: 
`PHP Warning:  Undefined array key "plugStatus" in /src/index.php on line 217'`

Could you look into this?

**Comment by db-EV** [comment]
I have a MeganE as well and for me it's working. Please run the debug.php and post the output here.

**Comment by DemianosHB** [comment]
> I have a MeganE as well and for me it's working. Please run the debug.php and post the output here.

I have another Idea, please let me verify this first. I've received the car on tuesday and it has never been charged after connecting it to myRenault. Even the the myRenault App does not show the plug status at the moment. 

I think after the first charge the issue will be gone. I will keep you updated.

Nevertheless I'd like to thank you for the script! It works really good and I like the fact that I can import the data to ABRP without using expensive services like Tronity :)

**Comment by db-EV** [comment]
Yes, this is the problem. It takes several day from activation of the car until all data is present on the Renault server. Therefore you don't see correct status in the My Renault app either.
