### ISSUE TITLE
no session found for this account

### ISSUE THREAD

**Issue by KremmyM** [db-EV/ZoePHP#31]
Hi i used the adapter sucessfuly in iobroker but now i identfied that it was not actualizing the data from my megane  etech any more.
I used it with the API key:

and i got the message int the iob protocoll
renault.0 | 2023-08-23 23:04:32.025 | error | No session found for this account

**Comment by db-EV** [comment]
Is the MyRenault app working? Tried to delete session file? You may even post output of the debug php here.
