### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by jumpjack** [db-EV/ZoePHP#8]
This script is very cool, but it completely lacks any security check!

I added this header to all the scripts, and I removed $username, $password and $vin from config.php:

```
if (!isset($_GET['pass'])) {
    die("Not authorized");
} else {
	if ($_GET['pass'] != "MYSCRIPTPASSWORD") { // password specific to these scripts
		die("Not authorized");
	}
}



if (!isset($_GET['username'])) {
    die("Please provide username for your MyRenault account.");
} else {
	$username = $_GET['username'];
}




if (!isset($_GET['password'])) {
    die("Please provide password for your MyRenault account.");
} else {
	$password = $_GET['password'];
}

if (!isset($_GET['vin'])) {
    die("Please provide VIN of your vehicle (it's in your MyRenault app)");
} else {
	$vin = $_GET['vin'];
}

```

Actually VIN can also be retrieved programmatically, but it is a little more complicated to implement.

**Comment by db-EV** [comment]
I disagree with you. The script shouldn't be available open on the internet - see last sentence in the readme:
"For security reasons I recommend to secure the script with basic authentication or other access restrictions."

Your integration of "security" opens more problems. There are no security checks on the input, maybe the script will be used without https.
